services:
  runner:
    image: myoung34/github-runner:latest
    container_name: aegira-creditapp-github-runner
    environment:
      REPO_URL: https://github.com/adnanamiruddin/docker-compose-aegira-creditapp
      RUNNER_NAME: aegira-creditapp-runner
      RUNNER_TOKEN: A3CYHBAPGJCAC7KP6MBKO7LKKRTKY
      LABELS: docker-local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/runner/data
    restart: unless-stopped
